import {config} from "dotenv";

config();

const {
    SERVER_PORT,
    SOCKET_PORT,
    CLIENT_URL,
    JWT_ACCESS_TOKEN_SECRET,
    JWT_REFRESH_TOKEN_SECRET,
    ENVIRNOMENT,
    BASE_DOMAIN,
    MONGO_DB_URL,
    COOKIE_PARSER_SECRET
} = process.env;

export const ENV_VAR = {
    SERVER_PORT:SERVER_PORT!,
    SOCKET_PORT:SOCKET_PORT!,
    CLIENT_URL:CLIENT_URL!,
    JWT_ACCESS_TOKEN_SECRET:JWT_ACCESS_TOKEN_SECRET!,
    JWT_REFRESH_TOKEN_SECRET:JWT_REFRESH_TOKEN_SECRET!,
    ENVIRNOMENT:ENVIRNOMENT! === 'DEVELOPMENT' ? false: true,
    BASE_DOMAIN:BASE_DOMAIN!,
    MONGO_DB_URL :MONGO_DB_URL!,
    COOKIE_PARSER_SECRET:COOKIE_PARSER_SECRET!

} 